addListGroup("categories", "category");
addList("category", "Please Choose", "", "0");
addList("category", "-------------", "", "1");
addList("category", "Corporate Governance", "1363", "Corporate Governance");
addList("Corporate Governance", "Please Choose", "", "0");
addList("Corporate Governance", "-------------", "", "1");
addList("Corporate Governance", "Board of Directors", "1364", "Board of Directors");
addList("Corporate Governance", "Code of Business Conduct", "1367", "Code of Conduct");
addList("Corporate Governance", "Committee Charters", "1365", "Committee Charters");
addList("Corporate Governance", "Corporate ByLaws", "1368", "Corporate ByLaws");
addList("Corporate Governance", "Management Team", "1366", "Management Team");
addList("category", "Calendar of Events", "1376", "Calendar of Events");
addList("Calendar of Events", "Please Choose", "", "0");
addList("Calendar of Events", "-------------", "", "1");
addList("Calendar of Events", "Earnings Releases", "1377", "Earnings Releases");
addList("Calendar of Events", "Shareholder Meetings", "1378", "Shareholder Meetings");
addList("category", "Email Subscription List", "1379", "Email Subscription");
addList("Email Subscription", "Please Choose", "", "0");
addList("Email Subscription", "-------------", "", "1");
addList("Email Subscription", "Subscribe to Financial Statements", "1383", "Financial Statements");
addList("Email Subscription", "Subscribe to Press Releases", "1382", "Press Releases");
addList("category", "Financial Reports", "1359", "Financial Reports");
addList("Financial Reports", "Please Choose", "", "0");
addList("Financial Reports", "-------------", "", "1");
addList("Financial Reports", "Form 10K", "1360", "Form 10K");
addList("Financial Reports", "Form 10Q", "1361", "Form 10Q");
addList("Financial Reports", "S&P Rating", "1362", "S&P Rating");
addList("category", "Press Releases", "1369", "Press Releases");
addList("Press Releases", "Please Choose", "", "0");
addList("Press Releases", "-------------", "", "1");
addList("Press Releases", "Current", "1370", "Current");
addList("Press Releases", "Historical", "1371", "Historical");
addList("category", "Shareholder Information", "1372", "Shareholder Infor");
addList("Shareholder Infor", "Please Choose", "", "0");
addList("Shareholder Infor", "-------------", "", "1");
addList("Shareholder Infor", "Form 8K", "1374", "Form 8K");
addList("Shareholder Infor", "Proxy Statement", "1373", "Proxy Statement");
addList("Shareholder Infor", "Transfer Agent", "1375", "Transfer Agent");
